### ISSUE TITLE
Thoughts on compatability for serial mode

### ISSUE THREAD

**Issue by mbalaam** [tillbaks/node-itach#1]
Thanks for your library. 

I have an IP2SL unit and have been experimenting with sending commands to a Meridian amplifier over RS232.

One issue I have discovered (and I am by no means an expert on serial comms) is that the response I get back is not captured cleanly by the data event. It comes in as packets, and the Meridian unit signifies that a packet has ended by adding a carriage return `\r'. I’m not sure if this is a standard or their own proprietary method. 

I have been playing around with the itach.js file and have added a check for a carriage return and only resolve when this is present. However I imagine that this may break ir compatability?

I’m going to make a fork and will open a PR at some point to share what I come up with.

**Comment by tillbaks** [comment]
Pretty sure itach devices always end with carriage return. That's why I slice it off in the code so the user of the module doesn't have to deal with it. Might be a good idea to check for it though as you said in case the response comes in multiple packets. I don't expect any issues tough but if you make a pull I'll test it on my IP2IR.

**Comment by mbalaam** [comment]
OK, cool. How my POC is handling it is to concatanate until finding a carriage return and then resolving once that is received. I’ll probably have some time over the weekend to to something tidier and make a PR.
